export const UI_STRINGS = {
  es: {
    appTitle: 'Visualizador Assessment',
    resetView: 'Restaurar Vista',
    langToggle: 'EN',
    hint: '🖱️ Arrastra para mover • Arrastra el fondo para desplazar • Rueda para zoom',
    tools: 'Herr.',
    note: 'Nota',
    questions: 'Preguntas',
    view: 'Vista',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    newBoard: 'Nuevo tablero',
    newBoardName: 'Nombre del tablero',
    newBoardPlaceholder: 'Mi ruta de visado...',
    deleteBoard: 'Eliminar tablero',
    deleteBoardConfirm: '¿Eliminar este tablero personalizado?',
    renameBoard: 'Renombrar',
    addNode: 'Añadir nodo',
    nodeTypes: {
      start: 'Inicio',
      filter: 'Filtro',
      branch: 'Rama',
      result: 'Resultado',
      error: 'Error',
    },
    connectMode: 'Conectar',
    connectModeHint: 'Haz clic en el nodo origen, luego en el destino',
    connectLabel: 'Etiqueta de conexión (opcional)',
    deleteNode: 'Eliminar nodo',
    editTitle: 'Editar título',
    editText: 'Editar texto',
    save: 'Guardar',
    cancel: 'Cancelar',
    edit: 'Editar',
    delete: 'Eliminar',
    doubleClickToEdit: 'Doble clic para registrar edición',
    doubleClickToEditTitle: 'Doble clic para editar título',
    addPostIt: 'Añadir nota Post-it',
    addQuestionsCard: 'Añadir tarjeta de preguntas',
    exportJSON: 'Exportar JSON',
    importJSON: 'Importar JSON',
    deleteCard: 'Eliminar tarjeta',
    invalidJSON: 'JSON inválido',
    noQuestionsYet: 'Sin preguntas aún. Añade una abajo.',
    noOptionsYet: 'Sin opciones aún.',
    viewEditOptions: 'Ver/editar opciones',
    clickToToggle: 'Clic para cambiar',
    qualifies: '✓ Califica',
    disqualifies: '✗ No califica',
    newOption: 'Nueva opción...',
    typeQuestion: 'Escribe una pregunta...',
    addQuestion: 'Añadir',
    questionTypes: { yes_no: 'Sí/No', multiple: 'Múltiple', single: 'Única' },
    commentPlaceholder: 'Escribe tu comentario aquí...',
    customBoardHint: '✏️ Tablero personalizado — arrastra, conecta y edita nodos libremente',
    tabs: {
      regularizacion: 'Reg. Extraordinaria 2026',
      nomad: 'Nómada Digital',
      work: 'Trabajo',
      student: 'Visado Estudios',
      non_lucrative: 'No Lucrativa',
      job_seeker: 'Búsqueda Empleo',
    },
  },
  en: {
    appTitle: 'Assessment Viewer',
    resetView: 'Reset View',
    langToggle: 'ES',
    hint: '🖱️ Drag nodes to move • Drag background to pan • Scroll to zoom',
    tools: 'Tools',
    note: 'Note',
    questions: 'Questions',
    view: 'View',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    newBoard: 'New board',
    newBoardName: 'Board name',
    newBoardPlaceholder: 'My visa path...',
    deleteBoard: 'Delete board',
    deleteBoardConfirm: 'Delete this custom board?',
    renameBoard: 'Rename',
    addNode: 'Add node',
    nodeTypes: {
      start: 'Start',
      filter: 'Filter',
      branch: 'Branch',
      result: 'Result',
      error: 'Error',
    },
    connectMode: 'Connect',
    connectModeHint: 'Click source node, then destination node',
    connectLabel: 'Connection label (optional)',
    deleteNode: 'Delete node',
    editTitle: 'Edit title',
    editText: 'Edit text',
    save: 'Save',
    cancel: 'Cancel',
    edit: 'Edit',
    delete: 'Delete',
    doubleClickToEdit: 'Double-click to log edit',
    doubleClickToEditTitle: 'Double-click to edit title',
    addPostIt: 'Add Post-it note',
    addQuestionsCard: 'Add assessment questions card',
    exportJSON: 'Export JSON',
    importJSON: 'Import JSON',
    deleteCard: 'Delete card',
    invalidJSON: 'Invalid JSON',
    noQuestionsYet: 'No questions yet. Add one below.',
    noOptionsYet: 'No options yet.',
    viewEditOptions: 'View/edit options',
    clickToToggle: 'Click to toggle',
    qualifies: '✓ Qualifies',
    disqualifies: '✗ Disqualifies',
    newOption: 'New option...',
    typeQuestion: 'Type a question...',
    addQuestion: 'Add',
    questionTypes: { yes_no: 'Yes/No', multiple: 'Multiple', single: 'Single' },
    commentPlaceholder: 'Write your comment here...',
    customBoardHint: '✏️ Custom board — freely drag, connect and edit nodes',
    tabs: {
      regularizacion: 'Extraordinary Reg. 2026',
      nomad: 'Digital Nomad',
      work: 'Work Visa',
      student: 'Student Visa',
      non_lucrative: 'Non-Lucrative',
      job_seeker: 'Job Seeker',
    },
  },
};
