export const UI_STRINGS = {
  es: {
    appTitle: 'Visualizador Assessment',
    resetView: 'Restaurar Vista',
    langToggle: 'EN',
    hint: '🖱️ Arrastra para mover • Arrastra el fondo para desplazar • Rueda para zoom',
    tools: 'Herr.',
    note: 'Nota',
    questions: 'Preguntas',
    view: 'Vista',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    tabs: {
      regularizacion: 'Reg. Extraordinaria 2026',
      nomad: 'Nómada Digital',
      work: 'Trabajo',
      student: 'Visado Estudios',
      non_lucrative: 'No Lucrativa',
      job_seeker: 'Búsqueda Empleo',
    },
  },
  en: {
    appTitle: 'Assessment Viewer',
    resetView: 'Reset View',
    langToggle: 'ES',
    hint: '🖱️ Drag nodes to move • Drag background to pan • Scroll to zoom',
    tools: 'Tools',
    note: 'Note',
    questions: 'Questions',
    view: 'View',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    tabs: {
      regularizacion: 'Extraordinary Reg. 2026',
      nomad: 'Digital Nomad',
      work: 'Work Visa',
      student: 'Student Visa',
      non_lucrative: 'Non-Lucrative',
      job_seeker: 'Job Seeker',
    },
  },
};
