export const UI_STRINGS = {
  es: {
    appTitle: 'Visualizador Assessment',
    resetView: 'Restaurar Vista',
    langToggle: 'EN',
    hint: '🖱️ Arrastra para mover • Arrastra el fondo para desplazar • Rueda para zoom',
    tools: 'Herr.',
    note: 'Nota',
    questions: 'Preguntas',
    view: 'Vista',
    zoomIn: 'Acercar',
    zoomOut: 'Alejar',
    newBoard: 'Nuevo tablero',
    newBoardName: 'Nombre del tablero',
    newBoardPlaceholder: 'Mi ruta de visado...',
    deleteBoard: 'Eliminar tablero',
    deleteBoardConfirm: '¿Eliminar este tablero personalizado?',
    renameBoard: 'Renombrar',
    addNode: 'Añadir nodo',
    nodeTypes: {
      start: 'Inicio',
      filter: 'Filtro',
      branch: 'Rama',
      result: 'Resultado',
      error: 'Error',
    },
    connectMode: 'Conectar',
    connectModeHint: 'Haz clic en el nodo origen, luego en el destino',
    connectLabel: 'Etiqueta de conexión (opcional)',
    deleteNode: 'Eliminar nodo',
    editTitle: 'Editar título',
    editText: 'Editar texto',
    customBoardHint: '✏️ Tablero personalizado — arrastra, conecta y edita nodos libremente',
    tabs: {
      regularizacion: 'Reg. Extraordinaria 2026',
      nomad: 'Nómada Digital',
      work: 'Trabajo',
      student: 'Visado Estudios',
      non_lucrative: 'No Lucrativa',
      job_seeker: 'Búsqueda Empleo',
    },
  },
  en: {
    appTitle: 'Assessment Viewer',
    resetView: 'Reset View',
    langToggle: 'ES',
    hint: '🖱️ Drag nodes to move • Drag background to pan • Scroll to zoom',
    tools: 'Tools',
    note: 'Note',
    questions: 'Questions',
    view: 'View',
    zoomIn: 'Zoom In',
    zoomOut: 'Zoom Out',
    newBoard: 'New board',
    newBoardName: 'Board name',
    newBoardPlaceholder: 'My visa path...',
    deleteBoard: 'Delete board',
    deleteBoardConfirm: 'Delete this custom board?',
    renameBoard: 'Rename',
    addNode: 'Add node',
    nodeTypes: {
      start: 'Start',
      filter: 'Filter',
      branch: 'Branch',
      result: 'Result',
      error: 'Error',
    },
    connectMode: 'Connect',
    connectModeHint: 'Click source node, then destination node',
    connectLabel: 'Connection label (optional)',
    deleteNode: 'Delete node',
    editTitle: 'Edit title',
    editText: 'Edit text',
    customBoardHint: '✏️ Custom board — freely drag, connect and edit nodes',
    tabs: {
      regularizacion: 'Extraordinary Reg. 2026',
      nomad: 'Digital Nomad',
      work: 'Work Visa',
      student: 'Student Visa',
      non_lucrative: 'Non-Lucrative',
      job_seeker: 'Job Seeker',
    },
  },
};
